#!/usr/bin/env ansible-playbook

- name: setup jekyll on ubuntu
  hosts: localhost

  tasks:

    - name: apt install
      become: yes
      apt:
        name:
          - ruby-full
          - build-essential
          - zlib1g-dev

    - name: gem install
      gem:
        name: "{{ item }}"
      loop:
          - jekyll
          - bundler
      when: '"GEM_HOME" in ansible_env'

